#!/bin/sh

mk_header() {
    printf '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"\n'
    printf '"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">\n'
    printf '<html>\n'
    printf '\n'
    printf '<head>\n'
    printf '	<title>%s</title>\n' "$title"
    printf '    <link rel="stylesheet" type="text/css" href="web.css" />\n'
    printf '</head>\n'
    printf '\n'
}

mk_thumbs() {
    rm -rf thumbs
    mkdir thumbs
    cp *.jpg thumbs/
    cd thumbs
    gm mogrify -size 120x120 *jpg -resize 120x120 +profile "*"
}

mk_img_link() {
    jpg="$1"
    link=$(echo "$jpg" | sed 's,\.jpg$,,')
    thumb="thumbs/$jpg"
    printf '<a href="%s">\n' "$jpg"
    printf '    <img src="%s" alt="%s"/>\n' "$thumb" "$link"
    printf '    %s\n' "$link"
    printf '    <br>\n'
    printf '</a>\n'
    printf '<br>\n'
}

title="$1"

mk_thumbs
mk_header

for i in *.jpg; do
    mk_img_link "$i"
done

printf '</body>\n'
